### PR TITLE
Fix issue with wrong path for view files.

### PR DESCRIPTION
**Pull request by mitogh**
There is an issue with mustache template having a wrong path since when the file path is created there is an assumptions that files are not going to have a dot `.` so there is a `.` added explicitly, in order to make sure there is only one doth on the path the the extension dots are removed from the extension.

### CODE REVIEW

**Comment by dmolsen** [comment]
Are you using the Node version of Pattern Lab? I get that this is an assumption but I'd rather have a consistent output for `patternExtension` rather than this fix. I may not have properly documented what the output should have been when we specced this change.

**Comment by mitogh** [comment]
Yep version 2 with styleguidekit-assets-default.

The mustache template are having an extra dot on the extension name.

**Comment by dmolsen** [comment]
I've asked Brian about this on the original spec issue for this feature. Depending on the response I may end up closing this PR without merging. I appreciate the heads up and fix though.

pattern-lab/the-spec#26

**Comment by mitogh** [comment]
Sounds good, thanks

**Comment by bmuenzenmeyer** [comment]
I need some time to review what's going on but it probably wont be until early next week. My head cold is getting the better of me. 

I thought I had patched this with https://github.com/pattern-lab/patternlab-node/commit/b7b8d4f2df420520d765dcc75b7b64b02dd88af3 which made it into [version `2.3.0`](https://github.com/pattern-lab/patternlab-node/releases/tag/v2.3.0) of Pattern Lab Node Core.

@mitogh what version is reported when you run `gulp patternlab:version` ?

There was a brief period of time (a couple days this week) where styleguidekitassets-default was ahead of PL/Node core, so it would depend on when you tried this, I think.

**Comment by bmuenzenmeyer** [comment]
@mitogh - ping. Attempting to understand if this is still an issue. As far as I can tell, it should not be on latest code and therefore does not require this PR.

**Comment by mitogh** [comment]
Sorry for the delay on this I'm going to test this tomorrow with the latest version.

I will let you know once I have more information on this, thank you for the following up.

**Comment by bmuenzenmeyer** [comment]
Closing this - I am certain the issues experienced were PL/Node hiccups.

**Pull request closed without merging**
